### ISSUE TITLE
搬家到 rbind

### ISSUE THREAD

**Issue by yihui** [rbind/choyang#1]
你好，如我在 https://cos.name/cn/topic/418547/ 中所说，我需要收集一些 blogdown 的例子，我可否邀请你把这个库搬到 https://github.com/rbind 组织下？搬过去之后你仍然会是这个库的管理员。

**Comment by yiluheihei** [comment]
ok， 当然可以

**Comment by yihui** [comment]
嗯，那好，你先把这个库转移给我，我再转移过去。如果不知道怎么转移的话，参见 https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/

**Comment by yihui** [comment]
好啦，搬家完成！多谢支持！
